version: "2"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ../:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27018:27017"
